/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'getting-started',
    {
      type: 'category',
      label: 'Tutorial',
      items: [
        'tutorial',
        'tutorial-part-1-units-points',
        'tutorial-part-2-outlines',
        'tutorial-part-3-pcbs',
        'tutorial-part-4-cases',
        'tutorial-part-5-next-steps'
      ],
    },
    'config-overview',
    'preprocessing',
    'units',
    'points',
    'outlines',
    'cases',
    'pcbs',
    'metadata',
    'formats',
    'next-steps'
  ],
};
